; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = firmware

[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps = 
	envirodiy/SDI-12@^2.3.2
	olikraus/U8g2@^2.35.19
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	jgromes/RadioLib@^7.1.2
	lewisxhe/PCF8563_Library@^1.0.1

[env:tx_node]
build_src_filter = +<shared/*> +<tx/*>
build_flags = 
	-DNODE_TYPE_TX
lib_deps = 
	${env.lib_deps}
	esphome/ESPAsyncWebServer-esphome@^3.3.0
	esphome/AsyncTCP-esphome@^2.1.4
	bblanchon/ArduinoJson@^7.0.0
	envirodiy/SDI-12@^2.3.2

[env:rx_gateway]
build_src_filter = +<shared/*> +<rx/*>
build_flags = 
	-DNODE_TYPE_RX
lib_deps = 
	${env.lib_deps}
	esphome/ESPAsyncWebServer-esphome@^3.3.0
	esphome/AsyncTCP-esphome@^2.1.4
	bblanchon/ArduinoJson@^7.0.0
	envirodiy/SDI-12@^2.3.2
